# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\University\Semester 6\Software Construction and Development\Project\AdvisorLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchAdvisorLogin(object):
    def setupUi(self, BatchAdvisorLogin):
        BatchAdvisorLogin.setObjectName("BatchAdvisorLogin")
        BatchAdvisorLogin.resize(459, 412)
        self.centralwidget = QtWidgets.QWidget(BatchAdvisorLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginPage = QtWidgets.QWidget(self.centralwidget)
        self.LoginPage.setEnabled(True)
        self.LoginPage.setGeometry(QtCore.QRect(0, 0, 461, 391))
        self.LoginPage.setAutoFillBackground(False)
        self.LoginPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LoginPage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginPage.setObjectName("LoginPage")
        self.LoginButton = QtWidgets.QPushButton(self.LoginPage)
        self.LoginButton.setGeometry(QtCore.QRect(190, 260, 91, 41))
        self.LoginButton.setStyleSheet("background-color: rgb(46, 172, 255);\n"
"font: 87 11pt \"Arial Black\";")
        self.LoginButton.setObjectName("LoginButton")
        self.PassLine = QtWidgets.QLineEdit(self.LoginPage)
        self.PassLine.setGeometry(QtCore.QRect(70, 210, 321, 31))
        self.PassLine.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.PassLine.setObjectName("PassLine")
        self.nameLine = QtWidgets.QLineEdit(self.LoginPage)
        self.nameLine.setGeometry(QtCore.QRect(70, 140, 321, 31))
        self.nameLine.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.nameLine.setObjectName("nameLine")
        self.AdvisorNamelabel = QtWidgets.QLabel(self.LoginPage)
        self.AdvisorNamelabel.setGeometry(QtCore.QRect(70, 110, 121, 16))
        self.AdvisorNamelabel.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";")
        self.AdvisorNamelabel.setObjectName("AdvisorNamelabel")
        self.IDlabel = QtWidgets.QLabel(self.LoginPage)
        self.IDlabel.setGeometry(QtCore.QRect(70, 180, 101, 16))
        self.IDlabel.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";")
        self.IDlabel.setObjectName("IDlabel")
        self.LoginDetailLabel = QtWidgets.QLabel(self.LoginPage)
        self.LoginDetailLabel.setGeometry(QtCore.QRect(50, 310, 361, 20))
        self.LoginDetailLabel.setText("")
        self.LoginDetailLabel.setObjectName("LoginDetailLabel")
        self.widget_2 = QtWidgets.QWidget(self.LoginPage)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 461, 81))
        self.widget_2.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(180, 30, 111, 31))
        self.label.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";\n"
"background-color: rgb(66, 167, 255);\n"
"")
        self.label.setObjectName("label")
        self.LoginDetailLabel_2 = QtWidgets.QLabel(self.LoginPage)
        self.LoginDetailLabel_2.setGeometry(QtCore.QRect(140, 340, 91, 20))
        self.LoginDetailLabel_2.setObjectName("LoginDetailLabel_2")
        self.LoginStudent = QtWidgets.QPushButton(self.LoginPage)
        self.LoginStudent.setGeometry(QtCore.QRect(230, 340, 41, 21))
        self.LoginStudent.setStyleSheet("background-color: rgb(46, 172, 255);\n"
"font: 75 10pt \"Arial Narrow\";")
        self.LoginStudent.setObjectName("LoginStudent")
        self.widget_2.raise_()
        self.LoginButton.raise_()
        self.PassLine.raise_()
        self.nameLine.raise_()
        self.AdvisorNamelabel.raise_()
        self.IDlabel.raise_()
        self.LoginDetailLabel.raise_()
        self.LoginDetailLabel_2.raise_()
        self.LoginStudent.raise_()
        BatchAdvisorLogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BatchAdvisorLogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        BatchAdvisorLogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BatchAdvisorLogin)
        self.statusbar.setObjectName("statusbar")
        BatchAdvisorLogin.setStatusBar(self.statusbar)

        self.retranslateUi(BatchAdvisorLogin)
        QtCore.QMetaObject.connectSlotsByName(BatchAdvisorLogin)

    def retranslateUi(self, BatchAdvisorLogin):
        _translate = QtCore.QCoreApplication.translate
        BatchAdvisorLogin.setWindowTitle(_translate("BatchAdvisorLogin", "MainWindow"))
        self.LoginButton.setText(_translate("BatchAdvisorLogin", "login"))
        self.AdvisorNamelabel.setText(_translate("BatchAdvisorLogin", "Name:"))
        self.IDlabel.setText(_translate("BatchAdvisorLogin", "Password:"))
        self.label.setText(_translate("BatchAdvisorLogin", "Batch Advisor"))
        self.LoginDetailLabel_2.setText(_translate("BatchAdvisorLogin", "login as student?"))
        self.LoginStudent.setText(_translate("BatchAdvisorLogin", "login"))
