# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\University\Semester 6\Software Construction and Development\Project\AdvisorMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvisorMenu(object):
    def setupUi(self, AdvisorMenu):
        AdvisorMenu.setObjectName("AdvisorMenu")
        AdvisorMenu.resize(460, 412)
        self.centralwidget = QtWidgets.QWidget(AdvisorMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginPage = QtWidgets.QWidget(self.centralwidget)
        self.LoginPage.setEnabled(True)
        self.LoginPage.setGeometry(QtCore.QRect(0, 0, 461, 391))
        self.LoginPage.setAutoFillBackground(False)
        self.LoginPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LoginPage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginPage.setObjectName("LoginPage")
        self.widget_2 = QtWidgets.QWidget(self.LoginPage)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 461, 81))
        self.widget_2.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(180, 30, 121, 31))
        self.label.setStyleSheet("font: 63 16pt \"Sitka Display Semibold\";\n"
"background-color: rgb(66, 167, 255);\n"
"")
        self.label.setObjectName("label")
        self.addCourse = QtWidgets.QPushButton(self.LoginPage)
        self.addCourse.setGeometry(QtCore.QRect(70, 160, 321, 51))
        self.addCourse.setStyleSheet("background-color: rgb(66, 167, 255);\n"
"font: 63 16pt \"Sitka Display Semibold\";")
        self.addCourse.setObjectName("addCourse")
        self.UpdateGrade = QtWidgets.QPushButton(self.LoginPage)
        self.UpdateGrade.setGeometry(QtCore.QRect(70, 220, 321, 51))
        self.UpdateGrade.setStyleSheet("background-color: rgb(66, 167, 255);\n"
"font: 63 16pt \"Sitka Display Semibold\";")
        self.UpdateGrade.setObjectName("UpdateGrade")
        AdvisorMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdvisorMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        AdvisorMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdvisorMenu)
        self.statusbar.setObjectName("statusbar")
        AdvisorMenu.setStatusBar(self.statusbar)

        self.retranslateUi(AdvisorMenu)
        QtCore.QMetaObject.connectSlotsByName(AdvisorMenu)

    def retranslateUi(self, AdvisorMenu):
        _translate = QtCore.QCoreApplication.translate
        AdvisorMenu.setWindowTitle(_translate("AdvisorMenu", "MainWindow"))
        self.label.setText(_translate("AdvisorMenu", "Batch Advisor"))
        self.addCourse.setText(_translate("AdvisorMenu", "Add Course"))
        self.UpdateGrade.setText(_translate("AdvisorMenu", "Update Students Grade"))
