# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\University\Semester 6\Software Construction and Development\Project\CourseRegistered.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CourseRegistered(object):
    def setupUi(self, CourseRegistered):
        CourseRegistered.setObjectName("CourseRegistered")
        CourseRegistered.resize(459, 412)
        self.centralwidget = QtWidgets.QWidget(CourseRegistered)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginPage = QtWidgets.QWidget(self.centralwidget)
        self.LoginPage.setEnabled(True)
        self.LoginPage.setGeometry(QtCore.QRect(0, 0, 461, 391))
        self.LoginPage.setAutoFillBackground(False)
        self.LoginPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LoginPage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginPage.setObjectName("LoginPage")
        self.LoginDetailLabel = QtWidgets.QLabel(self.LoginPage)
        self.LoginDetailLabel.setGeometry(QtCore.QRect(50, 310, 361, 20))
        self.LoginDetailLabel.setText("")
        self.LoginDetailLabel.setObjectName("LoginDetailLabel")
        self.widget_3 = QtWidgets.QWidget(self.LoginPage)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 461, 81))
        self.widget_3.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(180, 30, 111, 31))
        self.label_2.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";\n"
                                   "background-color: rgb(66, 167, 255);\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(self.LoginPage)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 421, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Content = QtWidgets.QWidget()
        self.Content.setObjectName("Content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Content)
        self.Content_Data = QtWidgets.QLabel(self.Content)
        self.Content_Data.setWordWrap(True)
        self.Content_Data.setObjectName("Content_Data")
        self.verticalLayout.addWidget(self.Content_Data)
        self.scrollArea.setWidget(self.Content)
        self.pushButton = QtWidgets.QPushButton(self.LoginPage)
        self.pushButton.setGeometry(QtCore.QRect(20, 340, 51, 23))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.widget_3.raise_()
        self.LoginDetailLabel.raise_()
        self.scrollArea.raise_()
        self.pushButton.raise_()
        CourseRegistered.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CourseRegistered)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        CourseRegistered.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CourseRegistered)
        self.statusbar.setObjectName("statusbar")
        CourseRegistered.setStatusBar(self.statusbar)
        # Set a monospaced font
        font = QtGui.QFont("Courier New", 10)
        self.Content_Data.setFont(font)
        
        self.retranslateUi(CourseRegistered)
        QtCore.QMetaObject.connectSlotsByName(CourseRegistered)

    def retranslateUi(self, CourseRegistered):
        _translate = QtCore.QCoreApplication.translate
        CourseRegistered.setWindowTitle(_translate("CourseRegistered", "MainWindow"))
        self.label_2.setText(_translate("CourseRegistered", "Batch Advisor"))
        self.pushButton.setText(_translate("CourseRegistered", "<<Back"))