# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\University\Semester 6\Software Construction and Development\Project\RegisteredCoursesbyStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisteredCoursesbyStudent(object):
    def setupUi(self, RegisteredCoursesbyStudent):
        RegisteredCoursesbyStudent.setObjectName("RegisteredCoursesbyStudent")
        RegisteredCoursesbyStudent.resize(459, 416)
        self.centralwidget = QtWidgets.QWidget(RegisteredCoursesbyStudent)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginPage = QtWidgets.QWidget(self.centralwidget)
        self.LoginPage.setEnabled(True)
        self.LoginPage.setGeometry(QtCore.QRect(0, 0, 461, 391))
        self.LoginPage.setAutoFillBackground(False)
        self.LoginPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LoginPage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginPage.setObjectName("LoginPage")
        self.LoginDetailLabel = QtWidgets.QLabel(self.LoginPage)
        self.LoginDetailLabel.setGeometry(QtCore.QRect(50, 310, 361, 20))
        self.LoginDetailLabel.setText("")
        self.LoginDetailLabel.setObjectName("LoginDetailLabel")
        self.widget_3 = QtWidgets.QWidget(self.LoginPage)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 461, 81))
        self.widget_3.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 181, 31))
        self.label_2.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";\n"
"background-color: rgb(66, 167, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(self.LoginPage)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 421, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Content = QtWidgets.QWidget()
        self.Content.setGeometry(QtCore.QRect(0, 0, 419, 239))
        self.Content.setObjectName("Content")
        self.Content_Data = QtWidgets.QLabel(self.Content)
        self.Content_Data.setGeometry(QtCore.QRect(20, 10, 381, 241))
        self.Content_Data.setText("")
        self.Content_Data.setScaledContents(False)
        self.Content_Data.setWordWrap(True)
        self.Content_Data.setObjectName("Content_Data")
        self.scrollArea.setWidget(self.Content)
        self.pushButton = QtWidgets.QPushButton(self.LoginPage)
        self.pushButton.setGeometry(QtCore.QRect(20, 350, 51, 23))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutScroll = QtWidgets.QVBoxLayout(self.Content)
        self.verticalLayoutScroll.addWidget(self.Content_Data)
        self.widget_3.raise_()
        self.LoginDetailLabel.raise_()
        self.scrollArea.raise_()
        self.pushButton.raise_()
        RegisteredCoursesbyStudent.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegisteredCoursesbyStudent)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        RegisteredCoursesbyStudent.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegisteredCoursesbyStudent)
        self.statusbar.setObjectName("statusbar")
        RegisteredCoursesbyStudent.setStatusBar(self.statusbar)

        self.retranslateUi(RegisteredCoursesbyStudent)
        QtCore.QMetaObject.connectSlotsByName(RegisteredCoursesbyStudent)

    def retranslateUi(self, RegisteredCoursesbyStudent):
        _translate = QtCore.QCoreApplication.translate
        RegisteredCoursesbyStudent.setWindowTitle(_translate("RegisteredCoursesbyStudent", "MainWindow"))
        self.label_2.setText(_translate("RegisteredCoursesbyStudent", "Student Registeration"))
        self.pushButton.setText(_translate("RegisteredCoursesbyStudent", "<<Back"))
