# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\University\Semester 6\Software Construction and Development\Project\Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourseRegister(object):
    def setupUi(self, CourseRegister):
        CourseRegister.setObjectName("CourseRegister")
        CourseRegister.resize(459, 409)
        self.centralwidget = QtWidgets.QWidget(CourseRegister)
        self.centralwidget.setObjectName("centralwidget")
        self.RegisterCourse = QtWidgets.QWidget(self.centralwidget)
        self.RegisterCourse.setEnabled(True)
        self.RegisterCourse.setGeometry(QtCore.QRect(0, 0, 471, 391))
        self.RegisterCourse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.RegisterCourse.setInputMethodHints(QtCore.Qt.ImhNone)
        self.RegisterCourse.setObjectName("RegisterCourse")
        self.RegisterButton = QtWidgets.QPushButton(self.RegisterCourse)
        self.RegisterButton.setGeometry(QtCore.QRect(170, 280, 131, 41))
        self.RegisterButton.setStyleSheet("background-color: rgb(66, 167, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.RegisterButton.setObjectName("RegisterButton")
        self.CourseName = QtWidgets.QLineEdit(self.RegisterCourse)
        self.CourseName.setGeometry(QtCore.QRect(72, 120, 331, 41))
        self.CourseName.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.CourseName.setObjectName("CourseName")
        self.CourseID = QtWidgets.QLineEdit(self.RegisterCourse)
        self.CourseID.setGeometry(QtCore.QRect(70, 200, 331, 41))
        self.CourseID.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.CourseID.setObjectName("CourseID")
        self.CourseNamelabel = QtWidgets.QLabel(self.RegisterCourse)
        self.CourseNamelabel.setGeometry(QtCore.QRect(70, 90, 121, 21))
        self.CourseNamelabel.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";")
        self.CourseNamelabel.setObjectName("CourseNamelabel")
        self.CourseIDlabel = QtWidgets.QLabel(self.RegisterCourse)
        self.CourseIDlabel.setGeometry(QtCore.QRect(70, 170, 121, 21))
        self.CourseIDlabel.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";")
        self.CourseIDlabel.setObjectName("CourseIDlabel")
        self.messagealert = QtWidgets.QLabel(self.RegisterCourse)
        self.messagealert.setGeometry(QtCore.QRect(70, 360, 321, 21))
        self.messagealert.setText("")
        self.messagealert.setObjectName("messagealert")
        self.label_2 = QtWidgets.QLabel(self.RegisterCourse)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 231, 31))
        self.label_2.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";\n"
"background-color: rgb(66, 167, 255);")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.RegisterCourse)
        self.widget.setGeometry(QtCore.QRect(0, 0, 461, 81))
        self.widget.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.widget.setObjectName("widget")
        self.messagealert_2 = QtWidgets.QLabel(self.RegisterCourse)
        self.messagealert_2.setGeometry(QtCore.QRect(70, 330, 211, 21))
        self.messagealert_2.setObjectName("messagealert_2")
        self.pushButton = QtWidgets.QPushButton(self.RegisterCourse)
        self.pushButton.setGeometry(QtCore.QRect(290, 330, 41, 23))
        self.pushButton.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.RegisterCourse)
        self.label.setGeometry(QtCore.QRect(70, 250, 201, 16))
        self.label.setObjectName("label")
        self.click = QtWidgets.QPushButton(self.RegisterCourse)
        self.click.setGeometry(QtCore.QRect(270, 250, 61, 20))
        self.click.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.click.setObjectName("click")
        self.widget.raise_()
        self.RegisterButton.raise_()
        self.CourseName.raise_()
        self.CourseID.raise_()
        self.CourseIDlabel.raise_()
        self.messagealert.raise_()
        self.label_2.raise_()
        self.CourseNamelabel.raise_()
        self.messagealert_2.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.click.raise_()
        CourseRegister.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CourseRegister)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        CourseRegister.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CourseRegister)
        self.statusbar.setObjectName("statusbar")
        CourseRegister.setStatusBar(self.statusbar)

        self.retranslateUi(CourseRegister)
        QtCore.QMetaObject.connectSlotsByName(CourseRegister)

    def retranslateUi(self, CourseRegister):
        _translate = QtCore.QCoreApplication.translate
        CourseRegister.setWindowTitle(_translate("CourseRegister", "MainWindow"))
        self.RegisterButton.setText(_translate("CourseRegister", "Register Course"))
        self.CourseNamelabel.setText(_translate("CourseRegister", "Course Name:"))
        self.CourseIDlabel.setText(_translate("CourseRegister", "Course ID:"))
        self.label_2.setText(_translate("CourseRegister", "Student Registration Form"))
        self.messagealert_2.setText(_translate("CourseRegister", "Do you need any help to register course?"))
        self.pushButton.setText(_translate("CourseRegister", "help?"))
        self.label.setText(_translate("CourseRegister", "click here to see your registered courses"))
        self.click.setText(_translate("CourseRegister", "click here"))
